### PR TITLE
Ports FE to Vue CLI 3

### PR DESCRIPTION
**Pull request by mcculleydj**
left the old FE in place
probably introduced some issues but for the most part things seem to work and CLI 3 is the future.

### CODE REVIEW

**Comment by rtfreedman** [comment]
the first example could be improved by making the hitpoint calculation multiple steps. Probably going to have to switch the tabs to something else like a select control (even though they look cool) if I can't figure this tab thing out. Really don't like the multi-line boolean expressions though.

**Comment by mcculleydj** [comment]
Yea prettier is making some really strange decisions, but I think some of that code can be simplified and as you said you control the rc. My bet is that if we turn off having it care about line length some of that nonsense will stop. I think pick your lint rules and then try and make your formatter adhere to them. More research to do. The rc file was not a creation of the CLI so maybe delete it and start from scratch.

Is my version of vuetify different? Because I just copied and pasted the files from your code so there shouldn't be much difference. We could prototype this and see it work without any other code that could possibly interfere. Essentially you want tabs, such that you can add a tab and remove a tab at will without breaking and the normal functionality.

**Comment by rtfreedman** [comment]
I'll push to a branch with the code merged in. Something weird is going on with tabs. Worst case I switch to a Characters menu with a close button in the menu or maybe a select control with some added fanciness. Have to work these weird bugs out or switch to a different component.

Link to branch of code merged: https://github.com/rtfreedman/DMinimal/commits/mcculleydj-master

Should probably make a permanent "preview" branch if this is going to happen often enough.

**Comment by mcculleydj** [comment]
Just pushed up a nice sandbox at the route /test

I'm able to give you the behavior I think you want in the first example, but I think you should really consider the second approach. Let the tabs be for navigating between characters only... and position the UI inside the card... when you do this you are always deleting the active tab item.

You get a stupid animation in the first example when you delete tab0, with tab1 active. IMO this is a bug since if you delete tab4 with tab5 active... tab5 stays active without having its content fly in from the left.

**Comment by rtfreedman** [comment]
Pushed up both solutions to the local branch. There's some visual wonkiness (spacing between that and name) that's going on with the embedded close button. Still deciding which is better.

**Comment by mcculleydj** [comment]
Cool. After you merge, I'll re-fork... That rebase was a complete disaster. I think it will go smoother if I contribute smaller changes than converting the underlying CLI

**Comment by rtfreedman** [comment]
I added you as a contributor if you want it. Figured it would be easier if you have any PRs in the future. Going to also turn off push to master so it's easier to maintain (and since I'll do it unless I turn it off). Since I can't commit to this branch I've opened up a new PR if you want to review before merge.

**Comment by rtfreedman** [comment]
Also need to fix the prettier settings before the merge as well...

**Pull request closed without merging**
